config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'about' => 'home#about', as: 'home_about'
  get 'contact' => 'home#contact', as: 'home_contact'
  get 'privacy' => 'home#privacy', as: 'home_privacy'
  get 'site_policies' => 'home#site_policies', as: 'home_site_policies'
  get 'news' => 'home#news', as: 'home_news'
  get 'changes' => 'home#changes', as: 'home_changes'

  get 'contest' => 'home#contest', as: 'home_contest'
  get 'contest_rules' => 'home#contest_rules', as: 'home_contest_rules'
  get 'contest_prizes' => 'home#contest_prizes', as: 'home_contest_prizes'
  get 'sweeps' => 'home#sweeps', as: 'home_sweeps'
  get 'sweeps_rules' => 'home#sweeps_rules', as: 'home_sweeps_rules'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '/users/:user_id', module: 'users' do
    get 'profile' => 'profile#show', as: 'user_profile'

    resources :accounts, as: 'user_accounts' do
      collection do
        get :select
      end
    end

    resources :item_listings, as: 'user_item_listings' do
      collection do
        get :sales
        get :purchases
        get :offers
        post :cancel
      end

      member do
        get :delivered
        get :received
      end
    end
  end

  get 'items/update_subtypes', as: 'items_update_subtypes'
  get 'items/update_form', as: 'items_update_form'

  resources :items do
    collection do
      get :autocomplete
    end
  end

  resources :item_listings, only: [:index, :show] do
    collection do
      get :wtb
      get :wts
      get :wtt
    end

    member do
      get :bid
      get :buy
      get :offer
    end
  end

=begin
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :items do
        resources :traits
        resources :tiers
        resources :styles
        resources :set_bonuses
        resources :rarities
        resources :enchants
        resources :configurations
      end

      resources :games
      resources :items
      resources :item_listings
    end
  end
=end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  add_breadcrumb "Home", :root_path

  def index
  end

  def about
  end

  def contact
  end

  def privacy
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
%div
  %div.center-block(style="width: 742px;")
    %h2.page-header About Us

  %p
    ESOLoot.com, as of today, is not yet a company. It is a partnership between two individuals and was built in their spare time after full time day jobs, around their family time and in competition with other obligations. It is not yet complete. It is not yet perfect or flawless. The site is still being worked on and will continue to grow and improve over time.
    Our goal is to provide you with the highest quality product we can produce as quickly as we can deliver it. If we generate any funds during the early launch of this site will go towards hosting and, eventually, dedicating more of our time toward this product.

  %h3 Rick Parker
  %p
    Better known as Wykkyd, or Wykkyd Gaming, Rick is a military veteran and has been programming since 1986. He has a strong passion for games, especially MMORPGs. At times he takes this passion too far and turns his game time into another job; one that he normally doesn’t get paid for. His addon downloads on ESOUI.com have totaled to over a half million in just over a month since The Elder Scrolls Online launched. He prides himself in delivering quality products that meet the community’s needs and desires, and hopes that this website will become another way to give the community something that many of them have been asking for.

  %h3 Chris Tanner
  %p
    Plays video games and develops things!

app/views/home/changes.html.haml
%h4(style="font-weight: bold;") Recent changes

%h5 May 16 2014
%ul
  %li Can now select a listing duration
  %li Starting bid is no longer required
  %li Can now search by item type and style
  %li New Heavy, Medium, and Light Apparel item types
  %li Enchants now appear in item tooltips
  %li Fixed account selection bug on create listing page

%h5 May 14 2014
%ul
  %li Auction grids now show the server of the account with the item
  %li Selecting an account will now filter the auction grids to only show items for the matching server
  %li Default duration for new auctions is now three days
  %li Item list when creating a new auction is now sorted alphabetically
  %li
    Fixed bug that was causing duplicate items to be created when creating an auction

%h5 May 13 2014
%ul
  %li Errors creating item listings fixed
  %li Delivered items now properly show up in My Sales and My Purchases until marked received
  %li Received listings no longer show in My Listings

app/views/home/contact.html.haml
%div
  %div.center-block(style="width: 742px;")
    %h2.page-header Contact Us

  %p
    As this site is still in its fledgling stages, and still maintained and supported by two people with day jobs and families, contact and support will unfortunately be limited during daylight hours (eastern time).
  %p
    For all assistance please email esoloot@gmail.com and we will respond as soon as possible if your issue can be addressed. Please try to be as clear as possible in your email’s subject line so that we can better assist you. If possible, please include a screenshot of your issue when contacting us.

app/views/home/contest.html.haml
%div
  %div.center-block(style="width: 742px;")
    %h2.page-header Grand Opening ‘Conquer the Market’ Contest

    %p
      As a celebration of the birth of ESOLoot.com and in the interest of seeing which of you is the savviest economist and auctioneer we are hosting the first ever Conquer the Market contest. This contest is only available to Premium Members.  The contest entry period will run from May 30th 2014 at 9pm EST and will last until June 19th at midnight PST.
    %p
      The Premium Membership limitation is for three reasons.  One, if you’re a Premium member we think you’re a rather amazing person and we want to reward you for your faith in our product.  Two, since this contest will result in prizes that bear monetary value we also need to limit the number of participants somewhat, so that we’re not absolutely flooded and forced into personal bankruptcy (after all we’re not a business yet, we’re just normal people).  Three, the contest participation rules require some of the features that only Premium members have access to.

    %h3 Prizes

    %ol
      %li
        Prizes will scale based upon participation.
      %li
        Available prizes will consist of Razer gaming peripherals or equivalent Amazon Gift Cards and the value of those prizes will vary.
      %li
        Razer gaming devices are only available as prizes within the continental United States. Outside of the continental United States only Amazon Gift Cards will be available. If you are a resident of a country where you cannot spend Amazon Gift Cards please contact ESOLoot via esoloot@gmail.com before participating to see if we can find a viable alternative, should you win.
      %li
        Actual prizes can be found on ESOLoot.com’s <Conquer the Market Prize Watch> page.

    %h3 Rules of Participation

    %ol
      %li
        You must be 18 years of age or older (20 in the case of Japan).
      %li
        You must be a resident of a country where online Contests such as this are not prohibited.
      %li
        You must be a Premium Member
      %li
        You must have a Validated email address
      %li
        You must have at least one verified auction transaction, to confirm your game account information and your “uniqueness”.
      %li
        Your participation begins when you register for the Contest, following rules 1 through 5 above, during the Contest entry period mentioned above.
      %li
        Your participation ends TWENTY CALENDAR DAYS and your marketing skills will be gauged using the rest of the rules and regulations herein.

        %ol
          %li
            This means that if you register on May 21st at 10pm EST you would have until June 10th at 10pm to compete.
          %li
            This also means that if you Register on June 10th before time expires you would have until June 30th at the same clock time you registered to compete.
      %li
        Your entry alone is not enough. This is not a Sweepstakes. There is no random drawing. You must compete using the tools available on the website.
      %li
        How to compete:

        %ol
          %li
            Sell things (rules below) for normal market value as would be expected in any normal auction house.
          %li
            Buy things (rules below) for normal market value (or below, if you can find it) as would be expected in any normal auction house.
          %li
            Maintain as close to a 60%/40% profit/loss ratio as possible (45% of your sales amounts being spent on purchases). Note: This is to promote fairness, so that we don’t end up with a website full of nothing but people trying to sell and nobody buying.
      %li
        You may be disqualified if you:

        %ol
          %li
            Attempt to cheat the system by using multiple accounts to buy and sell from yourself
          %li
            Use guild-mates or friends to round-robin items between yourselves
          %li
            Buy and re-sell the same items for the same prices in an attempt to pad your numbers or otherwise attempt to “game the system”
          %li
            Please note that ESOLoot.com reserves the right to adjust the rules of disqualification over time in the case that new tactics or techniques are discovered during the course of the Contest which are deemed to be unfair or not in the spirit of honest competition.

    %h3 Rules for Selling an Auction (and having it qualify toward your standing):

    %ol
      %li
        It must be posted as a 1 day listing
      %li
        It may be for BID or BUYOUT or both
      %li
        It must be of total value GREATER than 100 gold
      %li
        It must be of total value LESS than 3,000 gold
      %li
        It must be of GREEN or BLUE quality OR full stacks of crafting materials, EXCLUDING the following:

        %ol
          %li
            EPIC crafting materials do NOT qualify
          %li
            LEGENDARY crafting materials do NOT qualify
          %li
            The following RACIAL MOTIFS do NOT qualify:

            %ol
              %li
                Racial Motifs 11: Ancient Elves
              %li
                Racial Motifs 12: Barbaric
              %li
                Racial Motifs 13: Primal
              %li
                Racial Motifs 14: Daedric
      %li
        It CAN be for an item you previously purchased through the website providing that:

        %ol
          %li
            The original sale delivery of your purchase was CONFIRMED
          %li
            The re-sale of the item includes a mark-up
          %li
            The purchase and sale do not involve the same parties

            %ol
              %li
                This includes the history of that item. Items that are sold repeatedly through a chain of people will not count for any of the persons involved beyond the first seller.
      %li
        You must actually deliver the sold item(s) to the purchaser through in-game mail via COD.
      %li
        The seller MUST return to the site to confirm receipt of the item for the price listed on your auction with no additional fees, delays or items.

    %h3 Rules for Buying an Auction (and having it qualify toward your standing):

    %ol
      %li
        Warning: You could be buying from your competition, so purchase wisely
      %li
        Purchases must be completed on the website
      %li
        The purchase can be for any item for sale on the website that is lesser than Legendary quality and if the item is a stackable crafting material it must be for a FULL STACK in order to count.
      %li
        The sale price that you pay must also be of reasonable market value, no outrageously overpriced items or outrageously underpriced items in order to pad your purchases. We will be watching the data and analyzing market value of items.
      %li
        Seller must deliver the item to you via in-game mail via COD.
      %li
        You must confirm receipt of the item on the website.

  %p.center-block(style="width: 200px;")
    = link_to "Terms & Conditions", home_contest_rules_path

app/views/home/index.html.haml
%div
  %div.center-block(style="width: 742px;")
    %h2.page-header Welcome!

    %h3 Contest delayed
    %p Due to technical issues the contest has been delayed. The contest will now begin May 30 at 9PM EST.
    %hr

    %p
      Thank you for visiting the new ESOLoot.com. As you might have noticed it’s not quite finished yet. It’s still a bit messy here or there and not all of our “day one” features are complete yet. We needed to host it somewhere while we worked out the last few features and kinks, so here you have it. Exposed for the world to see, this is the new ESOLoot.

    %p
      Our goal is to become The Elder Scrolls Online’s premier offline auction house. We’re intent on providing you with the best services and features. After all, we’re players too and we know what we would want to use on a site like this.

    %p
      So, bear with us as we clear the last of our scaffolding and prepare for our impending launch. It won’t be very long before you’ll be able to post your auctions, buy your goods and otherwise contribute to the game’s fledgling economy. We look forward to working with you to build the very best online auctioning system that any game has ever seen… over time, of course. ;)

    %br
    = link_to "Grand Opening Sweepstakes", home_sweeps_path

    %br
    = link_to "'Conquer The Market' Contest", home_contest_path

    %br
    = link_to "'Conquer The Market' Contest Prizes", home_contest_prizes_path

    %br
    %br

    .well.well-lg
      %h4(style="font-weight: bold;")
        Recent changes &nbsp;
        = link_to "Full list", home_changes_path, style: "font-size: 12px;"

      %h5 May 16 2014
      %ul
        %li Can now select a listing duration
        %li Starting bid is no longer required
        %li Can now search by item type and style
        %li New Heavy, Medium, and Light Apparel item types
        %li Enchants now appear in item tooltips
        %li Fixed account selection bug on create listing page

      %h5 May 14 2014
      %ul
        %li Auction grids now show the server of the account with the item
        %li Selecting an account will now filter the auction grids to only show items for the matching server
        %li Default duration for new auctions is now three days
        %li Item list when creating a new auction is now sorted alphabetically
        %li
          Fixed bug that was causing duplicate items to be created when creating an auction
%br
%br

app/views/home/news.html.haml
#news
  .contact-info.pull-left
    Contact: Rick “Wykkyd” Parker
    %br
    Wykkyd Gaming
    %br
    wykkyd.gaming@gmail.com

  .branding-box.pull-right
    %span.branding-text Wykkyd Gaming

  .clearfix

  %h1(style="font-family: 'Arial Black'; font-size: 54pt;") Press Release

  %h2 Wykkyd Gaming Presents: ESOLoot.com

  %h3 The Elder Scrolls Online’s newest Offline Auction House

  %p
    May 12, 2014:  ESOLoot.com has officially launched and is now open for business.  Only a limited set of features are available but more will be released over the course of the next two weeks.  The site’s grand opening is also accompanied by a sweepstakes to give away Premium Memberships and a Premium Member exclusive contest for Razer gear and Amazon Gift Cards.

  %p
    Rick Parker, a widely known Lua addon developer who operates under the online names of Wykkyd and Wykkyd Gaming, has partnered with friend and co-worker Chris Tanner to bring you their vision of how an offline auction house should be.  Rick’s more than half million downloads of his addons speaks to his ability to deliver products that the Elder Scrolls Online community appreciates.  While the site is still being developed, and is only a mere glimpse of the features yet to come, he felt it would benefit the user community as a whole to launch early and let them take advantage of an admittedly slim feature-set that still outpaces the current competition.

  %p
    The nine day Premium Membership sweepstakes giveaway, running from May 12, 2014 until May 20, 2014, is the developers’ way of saying “Welcome aboard!”  It also affords them a chance to complete development of the introductory Premium Membership perks and tools that many will find useful when participating in the ‘Conquer the Market’ contest.

  %p
    The ‘Conquer the Market’ contest’s entry period will run from May 21, 2014 and will remain open until June 10, 2014.  Each contestant will have twenty days from the date they register for the contest to rack up purchases and sales, following strict guidelines, to see who will be crowned Kingpin of the ESOLoot market. Prizes will include Razer gear and Amazon Gift Cards and will scale in value, and in number of prizes given, based upon the number of participants.  If enough contestants compete the grand prize may even be a New Razer Blade.

  %p
    Make sure to take a look at this new, exciting web offering and take advantage of the launch events (each subject to posted Terms & Conditions).

  .news-footer
    For Release 8 PM EST - May 12, 2014
%br
%br

app/views/home/privacy.html.haml
%div
  %div.center-block(style="width: 742px;")
    %h2.page-header Privacy Policy

  %p
    At ESOLoot we take your privacy seriously.  Any information you provide in the creation of your account or through Sweepstakes or Contest entries will remain in the sole possession of ESOLoot.com and will not be distributed to any individuals, companies or agencies of any kind without legal subpoena except in regards to ZeniMAX Media and ZeniMAX Online Studios.
  %p
    Information will be shared freely with ZeniMAX in order to assist them in upholding their Terms of Service and to aid in any efforts to investigate any matters they might require, including but not limited to: Reported scam attempts, Reported TOS-breaking activities and player abuse of any kind.

app/views/home/site_policies.html.haml
%div
  %div.center-block(style="width: 742px;")
    %h2.page-header Site Policies & Terms of Use

    %p By registering with this site you agree to use the provided auctioning features to buy and/or sell only legitimate in-game items/gold in trade for legitimate in-game items/gold and to abide by the terms and conditions outlined within Zenimax Online Studios’ Terms of Service.  This website is in no way to be used to convert game items or currency into real world cash, products or services.  Any attempt to do so will result in banning and will be reported to Zenimax Online Studios for whatever further action they might wish to take.

    %p By using this site you also agree to have your transaction history made available to Zenimax Online Studios at their discretion and in whatever format they choose to receive or request it in.  You also agree that your transactions and information will be used for internal reporting and calculations as deemed necessary to support the operation of the website.

app/views/home/sweeps.html.haml
%div
  %div.center-block(style="width: 742px;")
    %h2.page-header Grand Opening Sweepstakes!

    %p
      In celebration of our Grand Opening, ESOLoot is hosting a Sweepstakes for all new, confirmed members. Enter now and you could win a FREE PREMIUM MEMBERSHIP! 10 of you will win of there are at least 100 participants. 5 will win if there are at least 50 but less than 100. Only 1 will win if there are less than 50 participants! The Sweepstakes will run from the moment that the website becomes publicly available until May 21st at midnight PST. Only one entry is available per Membership. Entering early, or late, will not affect your chances of winning.

    %p
      Registering for Premium Membership during the Sweepstakes will NOT remove you from the Sweepstakes’ list of Entrants. If you are selected as a winner and have already paid for a Premium Membership your Premium Membership fee will be reimbursed to you. If reimbursement is, for any reason, not possible we will work with you to find other means of compensation.

    %h3 How do I enter?

    %p
      Create a normal account, validate your email address and complete at least 1 transaction using the auction system on the website. This is all free to you, so anyone with an Elder Scrolls Online game account can participate.

  %p.center-block(style="width: 200px;")
    = link_to "Terms & Conditions", home_sweeps_rules_path

app/views/home/sweeps_rules.html.haml
%pre
  ESOLoot Sweepstakes Rules & Conditions

  NO PURCHASE NECESSARY TO ENTER OR WIN
  Purchase does not increase chance of winning.
  The Prize: Free 1 Year Premium Membership or reimbursement of the fees associated with purchasing same, if such has already been purchased by the winning account-holder. No cash or other prize substitution permitted except at Sponsor's discretion. The prize is nontransferable. Any and all prize related expenses, including without limitation any and all federal, state, and/or local taxes shall be the sole responsibility of the winner.
  How to enter: You may enter the Sweepstakes through the ESOLoot.com’s Account information tab using a Standard or Premium membership once your email address has been validated and your game account has been confirmed.