config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'about' => 'home#about', as: 'home_about'
  get 'contact' => 'home#contact', as: 'home_contact'
  get 'privacy' => 'home#privacy', as: 'home_privacy'
  get 'site_policies' => 'home#site_policies', as: 'home_site_policies'
  get 'news' => 'home#news', as: 'home_news'
  get 'changes' => 'home#changes', as: 'home_changes'

  get 'contest' => 'home#contest', as: 'home_contest'
  get 'contest_rules' => 'home#contest_rules', as: 'home_contest_rules'
  get 'contest_prizes' => 'home#contest_prizes', as: 'home_contest_prizes'
  get 'sweeps' => 'home#sweeps', as: 'home_sweeps'
  get 'sweeps_rules' => 'home#sweeps_rules', as: 'home_sweeps_rules'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '/users/:user_id', module: 'users' do
    get 'profile' => 'profile#show', as: 'user_profile'

    resources :accounts, as: 'user_accounts' do
      collection do
        get :select
      end
    end

    resources :item_listings, as: 'user_item_listings' do
      collection do
        get :sales
        get :purchases
        get :offers
        post :cancel
      end

      member do
        get :delivered
        get :received
      end
    end
  end

  get 'items/update_subtypes', as: 'items_update_subtypes'
  get 'items/update_form', as: 'items_update_form'

  resources :items do
    collection do
      get :autocomplete
    end
  end

  resources :item_listings, only: [:index, :show] do
    collection do
      get :wtb
      get :wts
      get :wtt
    end

    member do
      get :bid
      get :buy
      get :offer
    end
  end

=begin
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :items do
        resources :traits
        resources :tiers
        resources :styles
        resources :set_bonuses
        resources :rarities
        resources :enchants
        resources :configurations
      end

      resources :games
      resources :items
      resources :item_listings
    end
  end
=end

end

app/models/item_listing_type.rb
class ItemListingType < ActiveRecord::Base
  has_many :item_listings

  BUY = 1
  SELL = 2
  TRADE = 3
end

app/controllers/item_listings_controller.rb
class ItemListingsController < ApplicationController
  before_action :authenticate_user!, only: [:bid, :buy, :offer]
  before_action :set_item_listing, only: [:show, :bid, :buy, :offer]
  before_action :set_current_account, only: [:bid, :buy, :offer]

  after_action :verify_authorized, only: [:show, :bid, :buy, :offer]

  layout 'item_listings'

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Auctions", :item_listings_path

  DEFAULT_SORTS = ['item_name asc', 'current_bid asc', 'buyout asc']

  # GET /item_listings
  # GET /item_listings.json
  def index
    redirect_to action: :wts
  end

  def wts
    ItemListing.expire_auctions

    if current_user.nil?
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wts.search(params[:q])
    else
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wts_for_server(selected_server_id).not_for_user(current_user).search(params[:q])
    end

    @q.sorts = DEFAULT_SORTS if @q.sorts.empty?
    @listings = @q.result.page(params[:page])

    add_breadcrumb "WTS", :wts_item_listings_path
  end

  def wtb
    ItemListing.expire_auctions

    if current_user.nil?
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wtb.search(params[:q])
    else
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wtb_for_server(selected_server_id).not_for_user(current_user).search(params[:q])
    end

    @q.sorts = DEFAULT_SORTS if @q.sorts.empty?
    @listings = @q.result.page(params[:page])

    add_breadcrumb "WTB", :wtb_item_listings_path
  end

  def wtt
    ItemListing.expire_auctions

    #@q = ItemListing.of_kind(ItemListingType::TRADE).search(params[:q])
    #@q.sorts = DEFAULT_SORTS if @q.sorts.empty?
    #@listings = @q.result.page(params[:page])

    add_breadcrumb "WTT", :wtt_item_listings_path
  end

  # Bid on an item offered for sale in /wts
  def bid
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render :nothing => true
    else
      ItemListing.transaction do
        @item_listing.place_bid(current_user, @current_account)
        UserBid.create(user: current_user, account: @current_account, item_listing: @item_listing, quantity: @item_listing.quantity, bid_amount: @item_listing.current_bid)
      end

      flash[:notice] = 'Bid successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # Buy an item offered for sale in /wts
  def buy
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render :nothing => true
    else
      ItemListing.transaction do
        @item_listing.purchase(current_user, @current_account)
        UserPurchase.create(user: current_user, account: @current_account, item_listing: @item_listing, quantity: @item_listing.quantity, cost: @item_listing.buyout)
      end

      flash[:notice] = 'Purchase successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # Offer an item to fill a request in /wtb or /wtt
  def offer
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render :nothing => true
    else
      ItemListing.transaction do
        @item_listing.offer(current_user, @current_account)
        UserOffer.create(user: current_user, account: @current_account, item_listing: @item_listing, quantity: @item_listing.quantity)
      end

      flash[:notice] = 'Offer successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # GET /item_listings/1
  # GET /item_listings/1.json
  def show
    authorize @item_listing
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_listing
      @item_listing = ItemListing.find(params[:id])
    end

    def set_current_account
      @current_account = Account.find(selected_account_id) if selected_account_id.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_listing_params
      params.require(:item_listing).permit(:user_id, :account_id, :item_id, :quantity, :starting_bid, :bid_increment,
                                            :current_bid, :buyout, :expiration_date, :item_listing_type_id, :item_listing_status_id,
                                            :cancellation_reason_id, :high_bidder_user_id, :high_bidder_account_id,
                                            :consumer_user_id, :consumer_account_id)
    end
end

app/controllers/users/item_listings_controller.rb
class Users::ItemListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item_listing, only: [:show, :edit, :update, :destroy, :delivered, :received]
  before_action :set_current_account, only: [:delivered, :received, :create]

  after_action :verify_authorized, only: [:show, :edit, :update, :destroy, :delivered, :received]

  add_breadcrumb "Home", :root_path
  add_breadcrumb "User", :user_profile_path
  add_breadcrumb "Auctions", :user_item_listings_path

  # GET /item_listings
  # GET /item_listings.json
  def index
    @q = ItemListing.active.for_user(current_user).search(params[:q])
    @item_listings = @q.result.page(params[:page])

    @q.sorts = ['item_listing_status_name asc'] if @q.sorts.empty?

    @cancellation_reasons = CancellationReason.all
  end

  def sales
    @q = ItemListing.sold_by_user(current_user).search(params[:q])
    @item_listings = @q.result.page(params[:page])

    @q.sorts = ['item_listing_status_name asc'] if @q.sorts.empty?

    @cancellation_reasons = CancellationReason.all

    add_breadcrumb "Sales", :sales_user_item_listings_path
  end

  def purchases
    @q = ItemListing.purchased_by_user(current_user).search(params[:q])
    @item_listings = @q.result.page(params[:page])

    @q.sorts = ['item_listing_status_name asc'] if @q.sorts.empty?

    @cancellation_reasons = CancellationReason.all

    add_breadcrumb "Purchases", :purchases_user_item_listings_path
  end

  # GET /item_listings/1
  # GET /item_listings/1.json
  def show
    authorize @item_listing
  end

  # GET /item_listings/new
  def new
    @item_listing = ItemListing.new
    @item_listing.item = Item.new

    add_breadcrumb "Create", :new_user_item_listing_path
  end

  # GET /item_listings/1/edit
  def edit
    authorize @item_listing

    add_breadcrumb "Edit", :edit_user_item_listing_path
  end

  # POST /item_listings
  # POST /item_listings.json
  def create
    @item_listing = ItemListing.new(item_listing_params)

    @item_listing.expiration_date = 3.days.from_now if @item_listing.expiration_date.nil?
    @item_listing.current_bid = @item_listing.starting_bid
    @item_listing.item_listing_status = ItemListingStatus.find(ItemListingStatus::LISTED)

    db_item = Item.where(
      name: @item_listing.item.name,
      item_type_id: @item_listing.item.item_type_id,
      item_subtype_id: @item_listing.item.item_subtype_id,
      rarity_id: @item_listing.item.rarity_id,
      style_id: @item_listing.item.style_id,
      level: @item_listing.item.level,
      veteran_level: @item_listing.item.veteran_level,
      set_bonus_trait_id: @item_listing.item.set_bonus_trait_id,
      researchable_trait_id: @item_listing.item.researchable_trait_id,
      enchant_1_id: @item_listing.item.enchant_1_id,
      enchant_2_id: @item_listing.item.enchant_2_id
      ).first

    @item_listing.item = db_item if db_item

    respond_to do |format|
      if @item_listing.save
        format.html { redirect_to user_item_listings_url(current_user), notice: 'Item listing was successfully created.' }
        format.json { render :show, status: :created, location: @item_listing }
      else
        format.html { render :new }
        format.json { render json: @item_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_listings/1
  # PATCH/PUT /item_listings/1.json
  def update
    authorize @item_listing

    respond_to do |format|
      if @item_listing.update(item_listing_params)
        format.html { redirect_to user_item_listing_url(current_user, @item_listing), notice: 'Item listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_listing }
      else
        format.html { render :edit }
        format.json { render json: @item_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    cancellation_params[:listings].each do |item_listing_id|
      item_listing = ItemListing.find(item_listing_id)

      item_listing.cancel(cancellation_params[:reason])
    end

    respond_to do |format|
      format.html { redirect_to user_item_listings_url, notice: 'Listings were successfully cancelled.' }
      format.js   { render :nothing => true }
    end
  end

  def delivered
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render nothing: true
    else
      ItemListing.transaction do
        @item_listing.delivered
        UserDelivery.create(user: current_user, account: @current_account, item_listing: @item_listing)

        @item_listing.consumer_account.update(validated: true)
      end

      #flash[:notice] = 'Delivery successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  def received
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render nothing: true
    else
      ItemListing.transaction do
        @item_listing.received
        UserReceived.create(user: current_user, account: @current_account, item_listing: @item_listing)

        @item_listing.consumer_account.update(validated: true)
      end

      #flash[:notice] = 'Receipt successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # DELETE /item_listings/1
  # DELETE /item_listings/1.json
  def destroy
    authorize @item_listing

    @item_listing.destroy

    respond_to do |format|
      format.html { redirect_to user_item_listings_url(current_user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_listing
      @item_listing = ItemListing.find(params[:id])
    end

    def set_current_account
      @current_account = Account.find(selected_account_id) if selected_account_id.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_listing_params
      params.require(:item_listing).permit(:user_id, :account_id, :item_id, :quantity, :starting_bid, :bid_increment,
                                            :current_bid, :buyout, :expiration_date, :item_listing_type_id, :item_listing_status_id,
                                            :cancellation_reason_id, :high_bidder_user_id, :high_bidder_account_id,
                                            :consumer_user_id, :consumer_account_id,
                                            item_attributes: [
                                              :user_id, :name, :item_type_id, :item_subtype_id, :rarity_id, :style_id, :level,
                                              :veteran_level, :set_bonus_trait_id, :researchable_trait_id,
                                              :enchant_1_id, :enchant_2_id, :enchant_1_value, :enchant_1_value_2, :enchant_2_value, :enchant_2_value_2,
                                              :damage, :armor
                                              ])

    end

    def cancellation_params
      params.require(:cancellation)
    end
end

app/helpers/item_listings_helper.rb
module ItemListingsHelper
  def expires_in(item_listing)
    exp = item_listing.expiration_date

    if exp > 24.hours.from_now
      return "Days"
    elsif exp > 12.hours.from_now
      return "Long"
    elsif exp > 6.hours.from_now
      return "Medium"
    else #if exp > 1.hour.from_now
      return "Short"
    end
  end

  def item_listing_durations
    if current_user.premium?
      [
        ItemListingDuration.new("6 hours", 0.25.days.from_now),
        ItemListingDuration.new("12 hours", 0.5.days.from_now),
        ItemListingDuration.new("1 day", 1.day.from_now),
        ItemListingDuration.new("3 days", 3.days.from_now),
        ItemListingDuration.new("7 days", 7.days.from_now)
      ]
    else
      [
        ItemListingDuration.new("3 days", 3.days.from_now),
        ItemListingDuration.new("7 days", 7.days.from_now)
      ]
    end
  end
end

app/views/item_listings/_item_grid.html.haml
%table#grid.table.table-striped.table-hover
  - if @listings.empty?
    %tr
      %td No listings found
  - else
    %tr
      %th= sort_link(search, :item_name, "Item")
      %th= sort_link(search, :account_server_name, "Server")
      %th= sort_link(search, :item_level, "Level")
      %th= sort_link(search, :item_style_name, "Style")
      %th= sort_link(search, :item_set_bonus_trait_name, "Set Trait")
      %th= sort_link(search, :item_researchable_trait_name, "Research Trait")
      %th= sort_link(search, :quantity, "Quantity")
      %th= sort_link(search, :current_bid, "Bid")
      %th= sort_link(search, :buyout, "Buyout")
      %th= sort_link(search, :expiration_date, "Ends In")
      -#
        %th= sort_link(search, :item_listing_status_name, "Status")
      %th
      %th

    - @listings.each do |item_listing|
      %tr
        %td(style="min-width: 280px;")
          %span(rel="popover" data-toggle="popover" data-content="#{ h render partial: 'items/tooltip', locals: { item: item_listing.item }}")
            = item_listing.item.name
        %td= item_listing.account.server.name
        %td= level_display(item_listing.item)
        %td= item_listing.item.style.try(:name)
        %td= item_listing.item.set_bonus_trait.try(:name)
        %td= item_listing.item.researchable_trait.try(:name)
        %td= item_listing.quantity
        %td.bid= item_listing.current_bid
        %td= item_listing.buyout
        %td= expires_in(item_listing)
        -#
          %td= item_listing.item_listing_status.name
        - if item_listing.buy? or item_listing.trade?
          %td
            - if policy(item_listing).offer?
              = link_to "Offer", offer_item_listing_path(item_listing), remote: true, id: "offer-#{item_listing.id}"
          %td
        - if item_listing.sell?
          %td
            - if policy(item_listing).buy?
              = link_to "Buy", buy_item_listing_path(item_listing), remote: true, id: "buy-#{item_listing.id}"
          %td
            - if policy(item_listing).bid?
              = link_to "Bid", bid_item_listing_path(item_listing), remote: true, id: "bid-#{item_listing.id}"

.pull-right
  = paginate @listings, remote: true

app/views/item_listings/_item_grid_search.html.haml
%li.pull-right
  = search_form_for search, url: search_url, html: {class: "form-inline pull-right"} do |f|
    %a(href="#" data-toggle="modal" data-target="#search-modal") Advanced

    .form-group.has-feedback
      = f.label :item_name_cont, class: "sr-only"
      = f.text_field :item_name_cont, class: "form-control", placeholder: "Enter item name"
      %span.glyphicon.glyphicon-search.form-control-feedback
    .form-group
      = f.submit 'Search', class: "btn btn-default"

  .clearfix
  %br

app/views/item_listings/_item_grid_search_modal.html.haml
#search-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
        %h4.modal-title Search Listings

      = search_form_for search, url: search_url, html: {class: "form-horizontal"} do |f|
        .modal-body
          .form-group
            = f.label :account_server_id, "Server", class: "control-label col-md-3"
            .col-md-9
              = f.collection_select :account_server_id_eq, Server.all, :id, :name, {prompt: true}, { class: "form-control" }

          .form-group
            = f.label :item_name_cont, "Name", class: "control-label col-md-3"
            .col-md-9
              = f.text_field :item_name_cont, class: "form-control"

          .form-group
            = f.label :item_level_gteq, "Level Range", class: "control-label col-md-3"
            .col-md-4
              = f.text_field :item_level_gteq, class: "form-control"
            = f.label :item_level_lteq, " - ", class: "control-label col-md-1"
            .col-md-4
              = f.text_field :item_level_lteq, class: "form-control"

          .form-group
            = f.label :item_item_type_id_eq, "Type", class: "control-label col-md-3"
            .col-md-4
              = f.collection_select :item_item_type_id_eq, ItemType.where(enabled: true), :id, :name, {prompt: true}, { class: "form-control item-form-type" }
            = f.label :item_item_subtype_id_eq, "Subtype", class: "control-label col-md-1 sr-only"
            .col-md-4
              = f.collection_select :item_item_subtype_id_eq, ItemSubtype.where(enabled: true), :id, :name, {prompt: true}, { class: "form-control item-form-subtype" }

          .form-group
            = f.label :item_rarity_id_eq, "Quality", class: "control-label col-md-3"
            .col-md-9
              = f.collection_select :item_rarity_id_eq, Rarity.all, :id, :name, {prompt: true}, { class: "form-control" }

          .form-group
            = f.label :item_style_id_eq, "Style", class: "control-label col-md-3"
            .col-md-9
              = f.collection_select :item_style_id_eq, Style.all, :id, :name, {prompt: true}, { class: "form-control" }

          .form-group
            = f.label :item_set_bonus_trait_id_eq, "Set Trait", class: "control-label col-md-3"
            .col-md-9
              = f.collection_select :item_set_bonus_trait_id_eq, SetBonusTrait.all, :id, :name, {prompt: true}, { class: "form-control" }

          .form-group
            = f.label :item_researchable_trait_id_eq, "Research Trait", class: "control-label col-md-3"
            .col-md-9
              = f.collection_select :item_researchable_trait_id_eq, ResearchableTrait.all, :id, :name, {prompt: true}, { class: "form-control" }

        .modal-footer
          %button.btn.btn-default(type="button" data-dismiss="modal") Close
          = button_tag "Search", class: "btn btn-primary"

app/views/item_listings/bid.js.erb
$('#bid-<%= @item_listing.id %>').parent().siblings('.bid').html('<%= @item_listing.current_bid %>');
$('#bid-<%= @item_listing.id %>').empty();

app/views/item_listings/buy.js.erb
$('#buy-<%= @item_listing.id %>').empty();
$('#bid-<%= @item_listing.id %>').empty();

app/views/item_listings/offer.js.erb
$('#offer-<%= @item_listing.id %>').fadeOut('fast', function() {
  $(this).parent().html('');
});

app/views/item_listings/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @item_listing.item_listing_type.name
%p
  %b Item:
  = @item_listing.item.name

%p
  %b Item level
  = @item_listing.item.level

= render partial: 'items/tooltip', locals: {item: @item_listing.item}

%p
  %b Quantity:
  = @item_listing.quantity
%p
  %b Starting bid:
  = @item_listing.starting_bid
%p
  %b Buyout:
  = @item_listing.buyout
%p
  %b Expiration Date:
  = @item_listing.expiration_date
%p
  %b Status:
  = @item_listing.item_listing_status.name

app/views/item_listings/wtb.html.haml
= content_for :item_listings_search_content do
  = render partial: 'item_grid_search', locals: { search: @q, search_url: wtb_item_listings_path }

#wtb
  = render partial: 'item_grid', locals: { search: @q }

= render partial: 'item_grid_search_modal', locals: { search: @q, search_url: wtb_item_listings_path }

app/views/item_listings/wtb.js.erb
$('#wtb').html('<%= escape_javascript(render partial: 'item_grid', locals: { search: @q }) %>');

app/views/item_listings/wts.html.haml
= content_for :item_listings_search_content do
  = render partial: 'item_grid_search', locals: { search: @q, search_url: wts_item_listings_path }

#wts
  = render partial: 'item_grid', locals: { search: @q }

= render partial: 'item_grid_search_modal', locals: { search: @q, search_url: wts_item_listings_path }

app/views/item_listings/wts.js.erb
$('#wts').html('<%= escape_javascript(render partial: 'item_grid', locals: { search: @q }) %>');

app/views/item_listings/wtt.html.haml
#wtt
  %p Coming soon

-#
  = content_for :item_listings_search_content do
    Test