config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'about' => 'home#about', as: 'home_about'
  get 'contact' => 'home#contact', as: 'home_contact'
  get 'privacy' => 'home#privacy', as: 'home_privacy'
  get 'site_policies' => 'home#site_policies', as: 'home_site_policies'
  get 'news' => 'home#news', as: 'home_news'
  get 'changes' => 'home#changes', as: 'home_changes'

  get 'contest' => 'home#contest', as: 'home_contest'
  get 'contest_rules' => 'home#contest_rules', as: 'home_contest_rules'
  get 'contest_prizes' => 'home#contest_prizes', as: 'home_contest_prizes'
  get 'sweeps' => 'home#sweeps', as: 'home_sweeps'
  get 'sweeps_rules' => 'home#sweeps_rules', as: 'home_sweeps_rules'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '/users/:user_id', module: 'users' do
    get 'profile' => 'profile#show', as: 'user_profile'

    resources :accounts, as: 'user_accounts' do
      collection do
        get :select
      end
    end

    resources :item_listings, as: 'user_item_listings' do
      collection do
        get :sales
        get :purchases
        get :offers
        post :cancel
      end

      member do
        get :delivered
        get :received
      end
    end
  end

  get 'items/update_subtypes', as: 'items_update_subtypes'
  get 'items/update_form', as: 'items_update_form'

  resources :items do
    collection do
      get :autocomplete
    end
  end

  resources :item_listings, only: [:index, :show] do
    collection do
      get :wtb
      get :wts
      get :wtt
    end

    member do
      get :bid
      get :buy
      get :offer
    end
  end

=begin
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :items do
        resources :traits
        resources :tiers
        resources :styles
        resources :set_bonuses
        resources :rarities
        resources :enchants
        resources :configurations
      end

      resources :games
      resources :items
      resources :item_listings
    end
  end
=end

end

app/models/item_listing_type.rb
class ItemListingType < ActiveRecord::Base
  has_many :item_listings

  BUY = 1
  SELL = 2
  TRADE = 3
end

app/controllers/item_listings_controller.rb
class ItemListingsController < ApplicationController
  before_action :authenticate_user!, only: [:bid, :buy, :offer]
  before_action :set_item_listing, only: [:show, :bid, :buy, :offer]
  before_action :set_current_account, only: [:bid, :buy, :offer]

  after_action :verify_authorized, only: [:show, :bid, :buy, :offer]

  layout 'item_listings'

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Auctions", :item_listings_path

  DEFAULT_SORTS = ['item_name asc', 'current_bid asc', 'buyout asc']

  # GET /item_listings
  # GET /item_listings.json
  def index
    redirect_to action: :wts
  end

  def wts
    ItemListing.expire_auctions

    if current_user.nil?
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wts.search(params[:q])
    else
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wts_for_server(selected_server_id).not_for_user(current_user).search(params[:q])
    end

    @q.sorts = DEFAULT_SORTS if @q.sorts.empty?
    @listings = @q.result.page(params[:page])

    add_breadcrumb "WTS", :wts_item_listings_path
  end

  def wtb
    ItemListing.expire_auctions

    if current_user.nil?
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wtb.search(params[:q])
    else
      @q = ItemListing.joins(item: [:item_type, :item_subtype], account: :server).wtb_for_server(selected_server_id).not_for_user(current_user).search(params[:q])
    end

    @q.sorts = DEFAULT_SORTS if @q.sorts.empty?
    @listings = @q.result.page(params[:page])

    add_breadcrumb "WTB", :wtb_item_listings_path
  end

  def wtt
    ItemListing.expire_auctions

    #@q = ItemListing.of_kind(ItemListingType::TRADE).search(params[:q])
    #@q.sorts = DEFAULT_SORTS if @q.sorts.empty?
    #@listings = @q.result.page(params[:page])

    add_breadcrumb "WTT", :wtt_item_listings_path
  end

  # Bid on an item offered for sale in /wts
  def bid
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render :nothing => true
    else
      ItemListing.transaction do
        @item_listing.place_bid(current_user, @current_account)
        UserBid.create(user: current_user, account: @current_account, item_listing: @item_listing, quantity: @item_listing.quantity, bid_amount: @item_listing.current_bid)
      end

      flash[:notice] = 'Bid successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # Buy an item offered for sale in /wts
  def buy
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render :nothing => true
    else
      ItemListing.transaction do
        @item_listing.purchase(current_user, @current_account)
        UserPurchase.create(user: current_user, account: @current_account, item_listing: @item_listing, quantity: @item_listing.quantity, cost: @item_listing.buyout)
      end

      flash[:notice] = 'Purchase successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # Offer an item to fill a request in /wtb or /wtt
  def offer
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render :nothing => true
    else
      ItemListing.transaction do
        @item_listing.offer(current_user, @current_account)
        UserOffer.create(user: current_user, account: @current_account, item_listing: @item_listing, quantity: @item_listing.quantity)
      end

      flash[:notice] = 'Offer successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # GET /item_listings/1
  # GET /item_listings/1.json
  def show
    authorize @item_listing
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_listing
      @item_listing = ItemListing.find(params[:id])
    end

    def set_current_account
      @current_account = Account.find(selected_account_id) if selected_account_id.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_listing_params
      params.require(:item_listing).permit(:user_id, :account_id, :item_id, :quantity, :starting_bid, :bid_increment,
                                            :current_bid, :buyout, :expiration_date, :item_listing_type_id, :item_listing_status_id,
                                            :cancellation_reason_id, :high_bidder_user_id, :high_bidder_account_id,
                                            :consumer_user_id, :consumer_account_id)
    end
end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  after_action :verify_authorized, except: [:index, :select]

  layout 'users/profile'

  add_breadcrumb "Home", :root_path
  add_breadcrumb "User", :user_profile_path
  add_breadcrumb "Accounts", :user_accounts_path

  def select
    if params[:select_account_id].present?
      account = Account.find(params[:select_account_id])

      session[:selected_account_id] = account.id
      session[:selected_server_id] = account.server_id
    else
      session[:selected_account_id] = nil
      session[:selected_server_id] = nil
    end

    head :no_content
  end

  # GET /accounts
  # GET /accounts.json
  def index
    @q = Account.for_user(current_user).search(params[:q])
    @q.sorts = ['server_name asc', 'account_key asc'] if @q.sorts.empty?
    @accounts = @q.result.page(params[:page])
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    authorize @account
  end

  # GET /accounts/new
  def new
    @account = Account.new

    authorize @account

    add_breadcrumb "Create", :new_user_account_path
  end

  # GET /accounts/1/edit
  def edit
    authorize @account

    add_breadcrumb "Edit", :edit_user_account_path
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    authorize @account

    respond_to do |format|
      if @account.save
        format.html { redirect_to user_account_url(current_user, @account), notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    authorize @account

    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to user_account_url(current_user, @account), notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    authorize @account

    @account.destroy
    respond_to do |format|
      format.html { redirect_to user_accounts_url(current_user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :account_key, :server_id, :validated)
    end
end

app/controllers/users/item_listings_controller.rb
class Users::ItemListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item_listing, only: [:show, :edit, :update, :destroy, :delivered, :received]
  before_action :set_current_account, only: [:delivered, :received, :create]

  after_action :verify_authorized, only: [:show, :edit, :update, :destroy, :delivered, :received]

  add_breadcrumb "Home", :root_path
  add_breadcrumb "User", :user_profile_path
  add_breadcrumb "Auctions", :user_item_listings_path

  # GET /item_listings
  # GET /item_listings.json
  def index
    @q = ItemListing.active.for_user(current_user).search(params[:q])
    @item_listings = @q.result.page(params[:page])

    @q.sorts = ['item_listing_status_name asc'] if @q.sorts.empty?

    @cancellation_reasons = CancellationReason.all
  end

  def sales
    @q = ItemListing.sold_by_user(current_user).search(params[:q])
    @item_listings = @q.result.page(params[:page])

    @q.sorts = ['item_listing_status_name asc'] if @q.sorts.empty?

    @cancellation_reasons = CancellationReason.all

    add_breadcrumb "Sales", :sales_user_item_listings_path
  end

  def purchases
    @q = ItemListing.purchased_by_user(current_user).search(params[:q])
    @item_listings = @q.result.page(params[:page])

    @q.sorts = ['item_listing_status_name asc'] if @q.sorts.empty?

    @cancellation_reasons = CancellationReason.all

    add_breadcrumb "Purchases", :purchases_user_item_listings_path
  end

  # GET /item_listings/1
  # GET /item_listings/1.json
  def show
    authorize @item_listing
  end

  # GET /item_listings/new
  def new
    @item_listing = ItemListing.new
    @item_listing.item = Item.new

    add_breadcrumb "Create", :new_user_item_listing_path
  end

  # GET /item_listings/1/edit
  def edit
    authorize @item_listing

    add_breadcrumb "Edit", :edit_user_item_listing_path
  end

  # POST /item_listings
  # POST /item_listings.json
  def create
    @item_listing = ItemListing.new(item_listing_params)

    @item_listing.expiration_date = 3.days.from_now if @item_listing.expiration_date.nil?
    @item_listing.current_bid = @item_listing.starting_bid
    @item_listing.item_listing_status = ItemListingStatus.find(ItemListingStatus::LISTED)

    db_item = Item.where(
      name: @item_listing.item.name,
      item_type_id: @item_listing.item.item_type_id,
      item_subtype_id: @item_listing.item.item_subtype_id,
      rarity_id: @item_listing.item.rarity_id,
      style_id: @item_listing.item.style_id,
      level: @item_listing.item.level,
      veteran_level: @item_listing.item.veteran_level,
      set_bonus_trait_id: @item_listing.item.set_bonus_trait_id,
      researchable_trait_id: @item_listing.item.researchable_trait_id,
      enchant_1_id: @item_listing.item.enchant_1_id,
      enchant_2_id: @item_listing.item.enchant_2_id
      ).first

    @item_listing.item = db_item if db_item

    respond_to do |format|
      if @item_listing.save
        format.html { redirect_to user_item_listings_url(current_user), notice: 'Item listing was successfully created.' }
        format.json { render :show, status: :created, location: @item_listing }
      else
        format.html { render :new }
        format.json { render json: @item_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_listings/1
  # PATCH/PUT /item_listings/1.json
  def update
    authorize @item_listing

    respond_to do |format|
      if @item_listing.update(item_listing_params)
        format.html { redirect_to user_item_listing_url(current_user, @item_listing), notice: 'Item listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_listing }
      else
        format.html { render :edit }
        format.json { render json: @item_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    cancellation_params[:listings].each do |item_listing_id|
      item_listing = ItemListing.find(item_listing_id)

      item_listing.cancel(cancellation_params[:reason])
    end

    respond_to do |format|
      format.html { redirect_to user_item_listings_url, notice: 'Listings were successfully cancelled.' }
      format.js   { render :nothing => true }
    end
  end

  def delivered
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render nothing: true
    else
      ItemListing.transaction do
        @item_listing.delivered
        UserDelivery.create(user: current_user, account: @current_account, item_listing: @item_listing)

        @item_listing.consumer_account.update(validated: true)
      end

      #flash[:notice] = 'Delivery successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  def received
    authorize @item_listing

    if @current_account.nil?
      flash[:error] = "Please select an account"
      render nothing: true
    else
      ItemListing.transaction do
        @item_listing.received
        UserReceived.create(user: current_user, account: @current_account, item_listing: @item_listing)

        @item_listing.consumer_account.update(validated: true)
      end

      #flash[:notice] = 'Receipt successful.'

      respond_to do |format|
        format.js
      end
    end
  end

  # DELETE /item_listings/1
  # DELETE /item_listings/1.json
  def destroy
    authorize @item_listing

    @item_listing.destroy

    respond_to do |format|
      format.html { redirect_to user_item_listings_url(current_user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_listing
      @item_listing = ItemListing.find(params[:id])
    end

    def set_current_account
      @current_account = Account.find(selected_account_id) if selected_account_id.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_listing_params
      params.require(:item_listing).permit(:user_id, :account_id, :item_id, :quantity, :starting_bid, :bid_increment,
                                            :current_bid, :buyout, :expiration_date, :item_listing_type_id, :item_listing_status_id,
                                            :cancellation_reason_id, :high_bidder_user_id, :high_bidder_account_id,
                                            :consumer_user_id, :consumer_account_id,
                                            item_attributes: [
                                              :user_id, :name, :item_type_id, :item_subtype_id, :rarity_id, :style_id, :level,
                                              :veteran_level, :set_bonus_trait_id, :researchable_trait_id,
                                              :enchant_1_id, :enchant_2_id, :enchant_1_value, :enchant_1_value_2, :enchant_2_value, :enchant_2_value_2,
                                              :damage, :armor
                                              ])

    end

    def cancellation_params
      params.require(:cancellation)
    end
end

app/helpers/item_listings_helper.rb
module ItemListingsHelper
  def expires_in(item_listing)
    exp = item_listing.expiration_date

    if exp > 24.hours.from_now
      return "Days"
    elsif exp > 12.hours.from_now
      return "Long"
    elsif exp > 6.hours.from_now
      return "Medium"
    else #if exp > 1.hour.from_now
      return "Short"
    end
  end

  def item_listing_durations
    if current_user.premium?
      [
        ItemListingDuration.new("6 hours", 0.25.days.from_now),
        ItemListingDuration.new("12 hours", 0.5.days.from_now),
        ItemListingDuration.new("1 day", 1.day.from_now),
        ItemListingDuration.new("3 days", 3.days.from_now),
        ItemListingDuration.new("7 days", 7.days.from_now)
      ]
    else
      [
        ItemListingDuration.new("3 days", 3.days.from_now),
        ItemListingDuration.new("7 days", 7.days.from_now)
      ]
    end
  end
end

app/views/users/item_listings/_form.html.haml
= simple_form_for [current_user, @item_listing], html: {class: "form-horizontal ui-form-wide center-block"} do |f|
  = f.error_notification

  = f.association :user, as: :hidden, input_html: { value: current_user.try(:id) }

  .form-inputs
    %h3 Listing
    .row
      .col-md-5= f.association :item_listing_type, label: "Type"
      .col-md-5.col-md-offset-1= f.association :account, collection: Account.where(user_id: current_user.try(:id))

    .row
      .col-md-5= f.input :starting_bid
      .col-md-5.col-md-offset-1= f.input :buyout

    .row
      .col-md-5= f.input :quantity
      .col-md-5.col-md-offset-1= f.input :expiration_date, collection: item_listing_durations, label_method: :name, value_method: :duration

    %h3 Item

    .row
      .col-md-11
        = select_tag "select_item_id",
                    options_from_collection_for_select(Item.all.order(:name), :id, :name, selected: @item_listing.try(:item).try(:id)),
                    prompt: "Select item",
                    onchange: "$.get('#{items_update_form_path}', { select_item_id: $('#select_item_id').val() });",
                    class: "form-control pull-right"
        %br


    = f.simple_fields_for :item do |item_form|
      = render partial: 'items/form_fields', locals: {f: item_form}

    =# f.input :bid_increment
    =# f.input :expiration_date
    =# f.association :item_listing_status, label: "Status"

  .form-actions
    = f.button :submit

app/views/users/item_listings/_purchases_grid.html.haml
- if @item_listings.empty?
  %table.table.table-striped
    %tr
      %td No listings found
- else
  %table.table.table-striped.table-hover
    %tr
      %th= sort_link(search, :item_name, "Item")
      %th= sort_link(search, :account_name, "Bought From")
      %th= sort_link(search, :quantity, "Quantity")
      %th= sort_link(search, :buyout, "Price Paid")
      %th= sort_link(search, :item_listing_status_name, "Status")
      %th

    - @item_listings.each do |item_listing|
      %tr
        %td(style="min-width: 280px;")
          %span(rel="popover" data-toggle="popover" data-content="#{ h render partial: 'items/tooltip', locals: { item: item_listing.item }}")
            = item_listing.item.name
        %td
          - if item_listing.delivered?
            = item_listing.account.try(:name)
        %td= item_listing.quantity
        %td= item_listing.buyout
        %td.status= item_listing.item_listing_status.name
        %td
          - if policy(item_listing).received?
            = link_to "Received", received_user_item_listing_path(current_user, item_listing), remote: true, id: "received-#{item_listing.id}"

.pull-right
  = paginate @item_listings, remote: true

app/views/users/item_listings/_sales_grid.html.haml
- if @item_listings.empty?
  %table.table.table-striped
    %tr
      %td No listings found
- else
  %table.table.table-striped.table-hover
    %tr
      %th= sort_link(search, :item_name, "Item")
      %th= sort_link(search, :consumer_account_name, "Sold From")
      %th= sort_link(search, :user_account_name, "Deliver To")
      %th= sort_link(search, :quantity, "Quantity")
      %th= sort_link(search, :buyout, "Price Paid")
      %th= sort_link(search, :item_listing_status_name, "Status")
      %th

    - @item_listings.each do |item_listing|
      %tr
        %td(style="min-width: 280px;")
          %span(rel="popover" data-toggle="popover" data-content="#{ h render partial: 'items/tooltip', locals: { item: item_listing.item }}")
            = item_listing.item.name
        %th= item_listing.consumer_account.try(:name)
        %th= item_listing.account.name
        %td= item_listing.quantity
        %td= item_listing.buyout
        %td.status= item_listing.item_listing_status.name
        %td
          - if policy(item_listing).delivered?
            = link_to "Delivered", delivered_user_item_listing_path(current_user, item_listing), remote: true, id: "delivered-#{item_listing.id}"

.pull-right
  = paginate @item_listings, remote: true

app/views/users/item_listings/delivered.js.erb
$('#delivered-<%= @item_listing.id %>').fadeOut('fast', function() {
  $(this).html('');
});

$('#delivered-<%= @item_listing.id %>').parent().siblings('.status').html('<%= @item_listing.item_listing_status.try(:name) %>');

app/views/users/item_listings/edit.html.haml
%h1 Edit Listing

= render 'form'

app/views/users/item_listings/index.html.haml
.row
  .col-md-6
    .btn-group
      = link_to 'New Item Listing', new_user_item_listing_path(current_user), class: "btn btn-default"
      - unless @item_listings.empty?
        %a.btn.btn-default(href="#" data-toggle="modal" data-target="#cancel-modal") Cancel Listings

  .col-md-6
    = search_form_for @q, url: user_item_listings_path(current_user), html: {class: "form-inline pull-right"} do |f|
      .form-group.has-feedback
        = f.label :item_name_cont, class: "sr-only"
        = f.text_field :item_name_cont, class: "form-control", placeholder: "Enter item name"
        %span.glyphicon.glyphicon-search.form-control-feedback
      .form-group
        = f.submit 'Search', class: "btn btn-default"

    .clearfix
    %br

.row
  #grid.col-md-12
    = render partial: 'item_grid', locals: { search: @q }

app/views/users/item_listings/index.js.erb
$('#grid').html('<%= escape_javascript(render partial: 'item_grid', locals: { search: @q }) %>');

app/views/users/item_listings/new.html.haml
%h1 New Listing

= render 'form'

app/views/users/item_listings/purchases.html.haml
%div
  = search_form_for @q, url: purchases_user_item_listings_path(current_user), html: {class: "form-inline pull-right"} do |f|
    .form-group.has-feedback
      = f.label :item_name_cont, class: "sr-only"
      = f.text_field :item_name_cont, class: "form-control", placeholder: "Enter item name"
      %span.glyphicon.glyphicon-search.form-control-feedback
    .form-group
      = f.submit 'Search', class: "btn btn-default"

  .clearfix

%br

#grid
  = render partial: 'purchases_grid', locals: { search: @q }

app/views/users/item_listings/purchases.js.erb
$('#grid').html('<%= escape_javascript(render partial: 'purchases_grid', locals: { search: @q }) %>');

app/views/users/item_listings/received.js.erb
$('#received-<%= @item_listing.id %>').fadeOut('fast', function() {
  $(this).html('');
});

$('#received-<%= @item_listing.id %>').parent().siblings('.status').html('<%= @item_listing.item_listing_status.try(:name) %>');

app/views/users/item_listings/sales.html.haml
%div
  = search_form_for @q, url: sales_user_item_listings_path(current_user), html: {class: "form-inline pull-right"} do |f|
    .form-group.has-feedback
      = f.label :item_name_cont, class: "sr-only"
      = f.text_field :item_name_cont, class: "form-control", placeholder: "Enter item name"
      %span.glyphicon.glyphicon-search.form-control-feedback
    .form-group
      = f.submit 'Search', class: "btn btn-default"

  .clearfix

%br

#grid
  = render partial: 'sales_grid', locals: { search: @q }

app/views/users/item_listings/sales.js.erb
$('#grid').html('<%= escape_javascript(render partial: 'sales_grid', locals: { search: @q }) %>');

app/views/users/item_listings/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @item_listing.item_listing_type.name
%p
  %b User:
  = @item_listing.user.email
%p
  %b Account:
  = @item_listing.account.name
%p
  %b Item:
  = @item_listing.item.name
%p
  %b Quantity:
  = @item_listing.quantity
%p
  %b Starting bid:
  = @item_listing.starting_bid
%p
  %b Buyout:
  = @item_listing.buyout
%p
  %b Expiration Date:
  = @item_listing.expiration_date
%p
  %b Status:
  = @item_listing.item_listing_status.name

=# link_to 'Edit', edit_user_item_listing_path(current_user, @item_listing)