config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'about' => 'home#about', as: 'home_about'
  get 'contact' => 'home#contact', as: 'home_contact'
  get 'privacy' => 'home#privacy', as: 'home_privacy'
  get 'site_policies' => 'home#site_policies', as: 'home_site_policies'
  get 'news' => 'home#news', as: 'home_news'
  get 'changes' => 'home#changes', as: 'home_changes'

  get 'contest' => 'home#contest', as: 'home_contest'
  get 'contest_rules' => 'home#contest_rules', as: 'home_contest_rules'
  get 'contest_prizes' => 'home#contest_prizes', as: 'home_contest_prizes'
  get 'sweeps' => 'home#sweeps', as: 'home_sweeps'
  get 'sweeps_rules' => 'home#sweeps_rules', as: 'home_sweeps_rules'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '/users/:user_id', module: 'users' do
    get 'profile' => 'profile#show', as: 'user_profile'

    resources :accounts, as: 'user_accounts' do
      collection do
        get :select
      end
    end

    resources :item_listings, as: 'user_item_listings' do
      collection do
        get :sales
        get :purchases
        get :offers
        post :cancel
      end

      member do
        get :delivered
        get :received
      end
    end
  end

  get 'items/update_subtypes', as: 'items_update_subtypes'
  get 'items/update_form', as: 'items_update_form'

  resources :items do
    collection do
      get :autocomplete
    end
  end

  resources :item_listings, only: [:index, :show] do
    collection do
      get :wtb
      get :wts
      get :wtt
    end

    member do
      get :bid
      get :buy
      get :offer
    end
  end

=begin
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :items do
        resources :traits
        resources :tiers
        resources :styles
        resources :set_bonuses
        resources :rarities
        resources :enchants
        resources :configurations
      end

      resources :games
      resources :items
      resources :item_listings
    end
  end
=end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ESO Loot</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container" id="main-container">
    <%= link_to image_tag("esoloot.jpg", alt: "ESO Loot", class: "center-block", id: "logo"), root_path %>

    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="main-navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Profile", user_profile_path(current_user) %></li>
          <% end %>

          <li><%= link_to "Auctions", item_listings_path %></li>

          <% if user_signed_in? %>
            <li><%= link_to "My Listings", user_item_listings_path(current_user) %></li>
            <li><%= link_to "My Sales", sales_user_item_listings_path(current_user) %></li>
            <li><%= link_to "My Purchases", purchases_user_item_listings_path(current_user) %></li>

            <% if current_user.admin? %>
              <li><%= link_to "Items", items_path %></li>
            <% end %>
          <% end %>
        </ul>

        <p id="user_nav" class="navbar-text navbar-right">
          <% if user_signed_in? %>
            <% unless current_user.accounts.empty? %>
              <%= select_tag "select_account_id",
                    options_from_collection_for_select(current_user.accounts, :id, :name, selected: selected_account_id),
                    prompt: "Select account",
                    onchange: "$.get('#{select_user_accounts_path(current_user)}', { select_account_id: $('#select_account_id').val() });",
                    class: "form-control"
              %>
            <% end %>
          <% end %>
        </p>
      </div>
    </nav>

    <div id="flash-messages">
      <% if notice %>
        <div class="alert alert-success fade in" data-alert="alert">
          <p><%= notice %></p>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-warning fade in" data-alert="alert">
          <p><%= alert %></p>
        </div>
      <% end %>
    </div>

    <%#
    <div class="center-block" style="width: 728px; height: 90px; background-color: #eee;">
      Banner
    </div>

    <br>
    %>

    <div>
      <ol class="breadcrumb pull-left">
        <%= render_breadcrumbs tag: :li, separator: "" %>
      </ol>

      <div class="pull-right">
        <% if user_signed_in? %>
          <%= link_to current_user.email, user_profile_path(current_user) %>&nbsp;&nbsp;
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "navbar-link" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => "navbar-link" %> or
          <%= link_to "sign in", new_user_session_path, :class => "navbar-link" %>
        <% end %>
      </div>

      <div class="clearfix"></div>
    </div>

    <%= content_for?(:content) ? yield(:content) : yield %>

    <div id="footer" class="center-block">
      <div class="container">
        <%= link_to "About", home_about_path %>&nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to "Contact Us", home_contact_path %>&nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to "Privacy Policy", home_privacy_path %>&nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to "Site Policies", home_site_policies_path %>&nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to "News", home_news_path %>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/item_listings.html.haml
= content_for :content do
  %ul.nav.nav-pills
    %li{class: ("active" if current_page?(wts_item_listings_path))}
      %a(href="#{wts_item_listings_path}") WTS
    %li{class: ("active" if current_page?(wtb_item_listings_path))}
      %a(href="#{wtb_item_listings_path}") WTB
    %li{class: ("active" if current_page?(wtt_item_listings_path))}
      %a(href="#{wtt_item_listings_path}") WTT
    = yield(:item_listings_search_content)

  = content_for?(:item_listings_content) ? yield(:item_listings_content) : yield

= render template: 'layouts/application'